# Generated by Django 3.2.12 on 2022-02-09 05:32

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RenameModel(
            old_name='Cuisine',
            new_name='CuisineType',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_types',
            field=models.ManyToManyField(to='restaurant.CuisineType'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dining_types',
            field=models.ManyToManyField(to='restaurant.DiningType'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='meal_types',
            field=models.ManyToManyField(to='restaurant.MealType'),
        ),
    ]
