# Generated by Django 3.2.12 on 2022-02-03 13:34

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default=True, null=True, upload_to=restaurant.models.product_photo_directory_path),
        ),
    ]
