# Generated by Django 3.2.12 on 2022-02-15 06:59

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.models.product_photo_directory_path),
        ),
    ]
