# Generated by Django 3.2.12 on 2022-02-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220209_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
