# Generated by Django 3.2.11 on 2022-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20220201_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('account-owner', 'Account Owner'), ('restaurant-admin', 'Restaurant Admin'), ('restaurant-manager', 'Restaurant Manager'), ('restaurant-finance', 'Restaurant Finance'), ('branch-manager', 'Branch Manager'), ('branch-staff', 'Branch Staff')], default='account-owner', max_length=50),
        ),
    ]
