# Generated by Django 3.2.11 on 2022-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
    ]
