# Generated by Django 3.2.12 on 2022-02-07 04:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('days', models.CharField(max_length=100, verbose_name='Days')),
                ('start_time', models.TimeField(verbose_name='Opening Time')),
                ('end_time', models.TimeField(verbose_name='Closing Time')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='Break Time starts at')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='Break Time ends at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.branch')),
            ],
            options={
                'verbose_name_plural': 'Opening Hours',
            },
        ),
    ]
