# Generated by Django 3.2.11 on 2022-02-01 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('free-package', 'Free'), ('low-package', 'Basic'), ('mid-package', 'Silver'), ('high-package', 'Gold')], default='free-package', max_length=20)),
                ('trial_starts_at', models.DateField(blank=True, null=True, verbose_name='Trial Start Date')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='Trial End Date')),
                ('subscription_starts_at', models.DateField(blank=True, null=True, verbose_name='Subscription Start Date')),
                ('subscription_ends_at', models.DateField(blank=True, null=True, verbose_name='Subscription End Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
