# Generated by Django 3.2.12 on 2022-02-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.package'),
        ),
    ]
